### ISSUE TITLE
Using Different Signals for the Optimisation 

### ISSUE THREAD

**Issue by andrewcztrack** [Hvass-Labs/FinanceOps#2]
Hi @Hvass-Labs !!

I hope your well.

I am interested in using different signals for the optimization.
Ie. if I have a model that forecasts data for the next quarter. Ie 60 data points ahead.

Can I use this for the optimisation.

Kind regards and thanks,
Andrew

**Comment by Hvass-Labs** [comment]
It is nice with a polite question for once :-) In the future you may wish to write more details so it is easier for people to understand exactly what you are talking about. I think you are referring to the portfolio optimization notebooks? They are intended as ideas for others to experiment with. Please try your modifications and report back here if you make any new discoveries that might be useful to others. I am closing this issue but you can continue to write here.
